# Generated by Django 4.1.7 on 2023-04-06 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Programme',
            field=models.CharField(choices=[('Scholarship', 'Scholarship'), ('Sponsored', 'Sponsored'), ('Full Bursary', 'Full Bursary'), ('Half Bursary', 'Half Bursary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
