# Generated by Django 4.1.7 on 2023-04-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0004_schooladministrator_role'),
        ('Enrollments', '0002_enrollment_programme_alter_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchoolAdministrators.schooladministrator'),
        ),
    ]
