# Generated by Django 4.1.7 on 2023-04-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollments', '0003_enrollment_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Programme',
        ),
    ]
