# Generated by Django 4.1.7 on 2023-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0003_schooladministrator_current_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladministrator',
            name='role',
            field=models.CharField(choices=[('Super', 'Super'), ('Staff', 'Staff')], max_length=10, null=True),
        ),
    ]
