# Generated by Django 4.1.7 on 2023-04-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SchoolAdministrators', '0004_schooladministrator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladministrator',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
