# Generated by Django 4.1.7 on 2023-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SchoolAdministrators', '0006_remove_schooladministrator_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladministrator',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'content_type__app_label__in': ['Reports']}, related_name='my_model_permissions', to='auth.permission'),
        ),
    ]
