# Generated by Django 4.1.7 on 2023-04-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Schools', '0020_school_parents_alter_school_administrators'),
        ('SchoolAdministrators', '0007_schooladministrator_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooladministrator',
            name='permissions',
        ),
        migrations.CreateModel(
            name='Adminship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ship', to='SchoolAdministrators.schooladministrator')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
                ('permissions', models.ManyToManyField(blank=True, limit_choices_to={'content_type__app_label__in': ['Reports']}, related_name='my_model_permissions', to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='schooladministrator',
            name='adminship',
            field=models.ManyToManyField(to='SchoolAdministrators.adminship'),
        ),
    ]
