# Generated by Django 4.1.7 on 2023-04-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SchoolAdministrators', '0008_remove_schooladministrator_permissions_adminship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminship',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'content_type__app_label__in': ['Reports', 'Examinations']}, related_name='my_model_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='schooladministrator',
            name='adminship',
            field=models.ManyToManyField(blank=True, to='SchoolAdministrators.adminship'),
        ),
    ]
