# Generated by Django 4.1.7 on 2023-04-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SchoolAdministrators', '0009_alter_adminship_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminship',
            name='Groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
