# Generated by Django 4.1.7 on 2023-04-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0010_adminship_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooladministrator',
            name='schools',
        ),
    ]
