# Generated by Django 4.1.7 on 2023-04-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0020_school_parents_alter_school_administrators'),
        ('SchoolAdministrators', '0012_schooladministrator_schools'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminship',
            unique_together={('Admin', 'School')},
        ),
    ]
