# Generated by Django 4.1.7 on 2023-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0013_alter_adminship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminship',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
