# Generated by Django 4.1.7 on 2023-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0014_adminship_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminship',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
