# Generated by Django 4.1.7 on 2023-04-27 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0016_adminship_unauthorized_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminship',
            name='Date_Authorised',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
