# Generated by Django 3.2 on 2023-05-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0018_remove_schooladministrator_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminship',
            name='permissions',
        ),
    ]
