# Generated by Django 4.1.7 on 2023-04-29 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0006_alter_subject_name_combination'),
        ('Schools', '0031_school_levels'),
        ('Classes', '0007_class_lessons_alter_class_class_teacher_and_more'),
        ('Teachers', '0013_teacher_past_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateTimeField(null=True)),
                ('To', models.DateTimeField(default=django.utils.timezone.now)),
                ('Classes', models.ManyToManyField(blank=True, to='Classes.class')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
                ('Subjects', models.ManyToManyField(blank=True, to='Subjects.subject')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher')),
            ],
        ),
    ]
