# Generated by Django 4.1.7 on 2023-03-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
        ('Events', '0002_event_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Classes',
            field=models.ManyToManyField(blank=True, to='Classes.class'),
        ),
    ]
