# Generated by Django 4.1.7 on 2023-04-20 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parents', '0004_parent_fees_payments'),
        ('Students', '0014_student_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parents.parent')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='Students.student')),
            ],
        ),
    ]
