# Generated by Django 4.1.7 on 2023-04-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0030_school_applications'),
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
    ]
