# Generated by Django 4.1.7 on 2023-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_alter_application_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
