# Generated by Django 4.1.7 on 2023-04-13 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendout',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
