# Generated by Django 4.1.7 on 2023-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0003_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendout',
            name='Number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
