# Generated by Django 4.1.7 on 2023-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Students', '0003_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sujects',
            field=models.ManyToManyField(blank=True, to='Subjects.subject'),
        ),
    ]
