# Generated by Django 4.1.7 on 2023-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_alter_report_scores'),
        ('Students', '0004_student_sujects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Reports',
            field=models.ManyToManyField(blank=True, to='Reports.report'),
        ),
    ]
