# Generated by Django 4.1.7 on 2023-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Students', '0005_student_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Sujects',
        ),
        migrations.AddField(
            model_name='student',
            name='Subjects',
            field=models.ManyToManyField(blank=True, to='Subjects.subject'),
        ),
    ]
