# Generated by Django 4.1.7 on 2023-03-17 06:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_remove_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Students/Photos'),
        ),
    ]
