# Generated by Django 4.1.7 on 2023-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0003_remove_parent_children_relationship_and_more'),
        ('Students', '0009_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, to='Parents.parent'),
        ),
    ]
