# Generated by Django 4.1.7 on 2023-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_student_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Programme',
            field=models.CharField(choices=[('Scholarship', 'Scholarship'), ('Sponsored', 'Sponsored'), ('Full Bursary', 'Full Bursary'), ('Half Bursary', 'Half Bursary')], max_length=100, null=True),
        ),
    ]
