# Generated by Django 4.1.7 on 2023-04-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollments', '0002_enrollment_programme_alter_enrollment_date'),
        ('Students', '0011_student_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Enrollments.enrollment'),
        ),
    ]
