# Generated by Django 4.1.7 on 2023-04-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_student_active_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Programme',
        ),
    ]
