# Generated by Django 4.1.7 on 2023-04-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0001_initial'),
        ('Students', '0013_remove_student_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programmes.programme'),
        ),
    ]
