# Generated by Django 4.1.7 on 2023-04-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0006_alter_subject_name_combination'),
        ('Students', '0014_student_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Combination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.combination'),
        ),
    ]
