# Generated by Django 4.1.7 on 2023-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationHistory', '0001_initial'),
        ('Students', '0015_student_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_history',
            field=models.ManyToManyField(blank=True, to='EducationHistory.educationhistory'),
        ),
    ]
