# Generated by Django 4.1.7 on 2023-05-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Streams', '0003_alter_stream_class_teacher'),
        ('Students', '0016_student_education_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Streams.stream'),
        ),
    ]
