# Generated by Django 4.1.7 on 2023-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0017_student_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True),
        ),
    ]
