# Generated by Django 3.2 on 2023-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0018_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='Students/Qr_Codes'),
        ),
    ]
