# Generated by Django 4.1.7 on 2023-03-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Streams', '0001_initial'),
        ('Schools', '0005_school_badge'),
        ('Classes', '0002_alter_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='Streams',
            field=models.ManyToManyField(to='Streams.stream'),
        ),
        migrations.AlterField(
            model_name='class',
            name='Name',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Middle', 'Middle'), ('Top', 'Top')], max_length=100),
        ),
    ]
