# Generated by Django 4.1.7 on 2023-03-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0004_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='From',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='To',
            field=models.TimeField(null=True),
        ),
    ]
