# Generated by Django 4.1.7 on 2023-03-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0008_remove_teacher_email'),
        ('Classes', '0005_class_from_class_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Class_Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher'),
        ),
    ]
