# Generated by Django 4.1.7 on 2023-04-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0012_workprofile_lessons'),
        ('Lessons', '0002_alter_lesson_unique_together'),
        ('Classes', '0006_class_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Lessons',
            field=models.ManyToManyField(blank=True, to='Lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='class',
            name='Class_Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='From',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='To',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
