# Generated by Django 4.1.7 on 2023-04-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0007_class_lessons_alter_class_class_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
