# Generated by Django 4.1.7 on 2023-05-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Levels', '0004_level_students'),
        ('Classes', '0008_class_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Levels.level'),
        ),
    ]
