# Generated by Django 4.1.7 on 2023-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0009_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Candidate_Class',
            field=models.BooleanField(default=False),
        ),
    ]
