# Generated by Django 4.1.7 on 2023-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='Requirements',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
