# Generated by Django 4.1.7 on 2023-04-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0028_school_patient_admissions'),
        ('Programmes', '0002_programme_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
    ]
