# Generated by Django 4.1.7 on 2023-04-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0003_programme_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='Requirements',
        ),
    ]
