# Generated by Django 4.1.7 on 2023-03-25 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reports', '0006_report_aggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.PositiveIntegerField(null=True)),
                ('To', models.PositiveIntegerField(null=True)),
                ('Score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.score')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
