# Generated by Django 4.1.7 on 2023-04-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0012_workprofile_lessons'),
        ('MarkSheets', '0001_initial'),
        ('Students', '0014_student_programme'),
        ('Tallies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tally',
            name='From',
        ),
        migrations.RemoveField(
            model_name='tally',
            name='To',
        ),
        migrations.RemoveField(
            model_name='tally',
            name='User',
        ),
        migrations.AddField(
            model_name='tally',
            name='Mark_Sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarkSheets.marksheet'),
        ),
        migrations.AddField(
            model_name='tally',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.student'),
        ),
        migrations.AddField(
            model_name='tally',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='tally',
            name='Score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
