# Generated by Django 4.1.7 on 2023-04-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0003_alter_grade_name'),
        ('Tallies', '0003_tally_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='Grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grading.grade'),
        ),
    ]
