# Generated by Django 4.1.7 on 2023-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PastPapers', '0003_alter_pastpaper_answers_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='Downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
