# Generated by Django 4.1.7 on 2023-04-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0007_class_lessons_alter_class_class_teacher_and_more'),
        ('PastPapers', '0004_alter_pastpaper_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.class'),
        ),
    ]
