# Generated by Django 4.1.7 on 2023-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PastPapers', '0005_pastpaper_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='Class',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Middle', 'Middle'), ('Top', 'Top'), ('Primary One', 'Primary One'), ('Primary Two', 'Primary Two'), ('Primary Three', 'Primary Three'), ('Primary Four', 'Primary Four'), ('Primary Five', 'Primary Five'), ('Primary Six', 'Primary Six'), ('Primary Seven', 'Primary Seven'), ('Senior One', 'Senior One'), ('Senior Two', 'Senior Two'), ('Senior Three', 'Senior Three'), ('Senior Four', 'Senior Four'), ('Senior Five', 'Senior Five'), ('Senior Six', 'Senior Six')], max_length=20, null=True),
        ),
    ]
