# Generated by Django 3.2 on 2023-05-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examinations', '0014_paper_results'),
        ('PastPapers', '0008_alter_pastpaper_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpaper',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='pastpaper',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='pastpaper',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='pastpaper',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='Paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examinations.examination'),
        ),
    ]
