# Generated by Django 3.2 on 2023-05-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examinations', '0014_paper_results'),
        ('PastPapers', '0009_auto_20230519_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='Paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examinations.paper'),
        ),
    ]
