# Generated by Django 3.2 on 2023-05-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PastPapers', '0010_alter_pastpaper_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpaper',
            name='Description',
        ),
    ]
