# Generated by Django 4.1.7 on 2023-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
        ('Recruitments', '0002_classrecruitment_school'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Schools',
            field=models.ManyToManyField(through='Recruitments.ClassRecruitment', to='Schools.school'),
        ),
    ]
