# Generated by Django 4.1.7 on 2023-02-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_school_students'),
        ('Classes', '0001_initial'),
        ('Streams', '0001_initial'),
        ('Subjects', '0001_initial'),
        ('Teachers', '0004_teacher_current_class_teacher_current_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.class')),
                ('School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school')),
                ('Stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Streams.stream')),
                ('Subjects', models.ManyToManyField(to='Subjects.subject')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='classes_taught', through='Teachers.WorkProfile', to='Classes.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Schools',
            field=models.ManyToManyField(related_name='work_profile', through='Teachers.WorkProfile', to='Schools.school'),
        ),
    ]
