# Generated by Django 4.1.7 on 2023-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_workprofile_teacher_classes_alter_teacher_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Schools',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_prifile',
            field=models.ManyToManyField(to='Teachers.workprofile'),
        ),
    ]
