# Generated by Django 4.1.7 on 2023-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_remove_teacher_schools_remove_teacher_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='work_prifile',
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_profile',
            field=models.ManyToManyField(to='Teachers.workprofile'),
        ),
    ]
