# Generated by Django 4.1.7 on 2023-03-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0007_remove_teacher_work_prifile_teacher_work_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
