# Generated by Django 4.1.7 on 2023-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0002_alter_lesson_unique_together'),
        ('Teachers', '0008_remove_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Lessons',
            field=models.ManyToManyField(blank=True, to='Lessons.lesson'),
        ),
    ]
