# Generated by Django 4.1.7 on 2023-03-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0009_teacher_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='current_school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_work_profile', to='Teachers.workprofile'),
        ),
    ]
