# Generated by Django 4.1.7 on 2023-03-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_class_class_teacher'),
        ('Teachers', '0010_remove_teacher_current_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprofile',
            name='Class',
        ),
        migrations.AddField(
            model_name='workprofile',
            name='Classes',
            field=models.ManyToManyField(blank=True, to='Classes.class'),
        ),
    ]
