# Generated by Django 4.1.7 on 2023-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0002_alter_lesson_unique_together'),
        ('Teachers', '0011_remove_workprofile_class_workprofile_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprofile',
            name='Lessons',
            field=models.ManyToManyField(blank=True, to='Lessons.lesson'),
        ),
    ]
