# Generated by Django 4.1.7 on 2023-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PastPapers', '0006_alter_pastpaper_class'),
        ('Teachers', '0012_workprofile_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Past_Papers',
            field=models.ManyToManyField(blank=True, to='PastPapers.pastpaper'),
        ),
    ]
