# Generated by Django 4.1.7 on 2023-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachingHistory', '0001_initial'),
        ('Teachers', '0013_teacher_past_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='TeachingHistory',
            field=models.ManyToManyField(blank=True, to='TeachingHistory.teachinghistory'),
        ),
    ]
