# Generated by Django 4.1.7 on 2023-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
