# Generated by Django 4.1.7 on 2023-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesManagement', '0006_paymentdue_compulsory'),
        ('Parents', '0003_remove_parent_children_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Fees_Payments',
            field=models.ManyToManyField(related_name='feespayments', to='FeesManagement.payment'),
        ),
    ]
