# Generated by Django 3.2 on 2023-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0005_parent_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='parent',
            name='Tel',
            field=models.IntegerField(null=True),
        ),
    ]
