# Generated by Django 3.2 on 2023-05-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesManagement', '0007_payment_paid_via'),
        ('Parents', '0006_auto_20230519_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Fees_Payments',
            field=models.ManyToManyField(blank=True, related_name='feespayments', to='FeesManagement.Payment'),
        ),
    ]
