# Generated by Django 3.2 on 2023-06-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0006_auto_20230601_0645'),
        ('Parents', '0007_alter_parent_fees_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='current_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subscriptions.subscription'),
        ),
    ]
