# Generated by Django 4.1.7 on 2023-04-14 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SchoolAdministrators', '0016_adminship_unauthorized_attempts'),
        ('Students', '0014_student_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Complications', models.TextField(max_length=10000)),
                ('Dismissed', models.DateTimeField(null=True)),
                ('Examined_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdministrators.schooladministrator')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
        ),
    ]
