# Generated by Django 4.1.7 on 2023-03-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0010_student_parents'),
        ('Parents', '0003_remove_parent_children_relationship_and_more'),
        ('Classes', '0006_class_class_teacher'),
        ('Schools', '0013_school_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=100)),
                ('Amount_Required', models.PositiveIntegerField(null=True)),
                ('Classes', models.ManyToManyField(blank=True, to='Classes.class')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mobile Money', 'Mobile Money'), ('Other', 'Other')], max_length=20)),
                ('Amount', models.PositiveIntegerField(null=True)),
                ('Due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeesManagement.paymentdue')),
                ('Students', models.ManyToManyField(blank=True, to='Students.student')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parents.parent')),
            ],
        ),
    ]
