# Generated by Django 4.1.7 on 2023-04-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Terms', '0001_initial'),
        ('FeesManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdue',
            name='Term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Terms.term'),
        ),
    ]
