# Generated by Django 4.1.7 on 2023-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesManagement', '0003_remove_payment_students_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdue',
            name='Payments',
            field=models.ManyToManyField(blank=True, to='FeesManagement.payment'),
        ),
    ]
