# Generated by Django 4.1.7 on 2023-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesManagement', '0005_payment_date_alter_paymentdue_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdue',
            name='Compulsory',
            field=models.BooleanField(default=False),
        ),
    ]
