# Generated by Django 4.1.7 on 2023-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesManagement', '0006_paymentdue_compulsory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Paid_Via',
            field=models.CharField(choices=[('School', 'School'), ('Mobile', 'Mobile')], max_length=100, null=True),
        ),
    ]
