# Generated by Django 4.1.7 on 2023-03-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0014_school_dues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Term One', 'Term One'), ('Term Two', 'Term Two'), ('Term Three', 'Term Three')], max_length=10)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
    ]
