# Generated by Django 4.1.7 on 2023-03-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Students', '0002_student_school'),
        ('Examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examinations.examination')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.PositiveIntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.report')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='Scores',
            field=models.ManyToManyField(to='Reports.score'),
        ),
        migrations.AddField(
            model_name='report',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
