# Generated by Django 4.1.7 on 2023-03-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_alter_report_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='Grade',
        ),
    ]
