# Generated by Django 4.1.7 on 2023-03-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0002_grade_value'),
        ('Reports', '0003_remove_score_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='Grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grading.grade'),
        ),
    ]
