# Generated by Django 4.1.7 on 2023-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_score_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Total_Score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
