# Generated by Django 4.1.7 on 2023-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_report_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Aggregate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
