# Generated by Django 4.1.7 on 2023-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0006_report_aggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Published',
            field=models.BooleanField(default=False),
        ),
    ]
