# Generated by Django 3.2 on 2023-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examinations', '0014_paper_results'),
        ('Reports', '0007_report_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Scores',
        ),
        migrations.AddField(
            model_name='report',
            name='Results',
            field=models.ManyToManyField(blank=True, to='Examinations.Result'),
        ),
    ]
