# Generated by Django 4.1.7 on 2023-02-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
        ('Recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecruitment',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
    ]
