# Generated by Django 4.1.7 on 2023-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBanks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='Potable_Digital_Formart',
            field=models.FileField(null=True, upload_to='QuestionBanks/pdf'),
        ),
    ]
