# Generated by Django 4.1.7 on 2023-04-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBanks', '0002_questionbank_potable_digital_formart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='Subject',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Drawing', 'Drawing'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer Studies', 'Computer Studies'), ('Social Studies', 'Social Studies'), ('Geography', 'Geography'), ('Christian Religious Education', 'Christian Religious Education'), ('Islamic Religious Education', 'Islamic Religious Education'), ('History', 'History'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Turkish', 'Turkish')], max_length=100),
        ),
    ]
