# Generated by Django 4.1.7 on 2023-04-24 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programmes', '0003_programme_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.programme')),
            ],
        ),
    ]
