# Generated by Django 4.1.7 on 2023-04-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0004_remove_programme_requirements'),
        ('Requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.programme')),
            ],
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
