# Generated by Django 4.1.7 on 2023-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requirements', '0002_requirement_delete_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='Quantity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
