# Generated by Django 4.1.7 on 2023-03-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0005_school_badge'),
        ('Classes', '0005_class_from_class_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('D1', 'D1'), ('D2', 'D2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('P7', 'P7'), ('P8', 'P8'), ('F9', 'F9'), ('A', 'A'), ('B', 'B')], max_length=100)),
                ('From', models.PositiveIntegerField(null=True)),
                ('To', models.PositiveIntegerField(null=True)),
                ('Classes', models.ManyToManyField(to='Classes.class')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('First Grade', 'First Grade'), ('Second Grade', 'Second Grade'), ('Third Grade', 'Third Grade'), ('Fourth Grade', 'Fourth Grade')], max_length=100)),
                ('From', models.PositiveIntegerField(null=True)),
                ('To', models.PositiveIntegerField(null=True)),
                ('Classes', models.ManyToManyField(to='Classes.class')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
    ]
