# Generated by Django 4.1.7 on 2023-03-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='Value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
