# Generated by Django 4.1.7 on 2023-03-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0002_grade_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Name',
            field=models.CharField(choices=[('D1', 'D1'), ('D2', 'D2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('P7', 'P7'), ('P8', 'P8'), ('F9', 'F9'), ('A', 'A'), ('B', 'B'), ('Ungraded', 'Ungraded')], max_length=100),
        ),
    ]
