# Generated by Django 4.1.7 on 2023-04-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examinations', '0004_examination_classes'),
        ('Classes', '0007_class_lessons_alter_class_class_teacher_and_more'),
        ('Tallies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.class')),
                ('Exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examinations.examination')),
                ('Tallies', models.ManyToManyField(to='Tallies.tally')),
            ],
        ),
    ]
