# Generated by Django 4.1.7 on 2023-04-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tallies', '0002_remove_tally_from_remove_tally_to_remove_tally_user_and_more'),
        ('Subjects', '0004_alter_subject_head_of_department_alter_subject_name'),
        ('MarkSheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.subject'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='Tallies',
            field=models.ManyToManyField(blank=True, to='Tallies.tally'),
        ),
    ]
