# Generated by Django 4.1.7 on 2023-03-11 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0005_school_badge'),
        ('Parents', '0002_parent_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Amount', models.PositiveIntegerField(choices=[(30000, 30000)])),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parents.parent')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
    ]
