# Generated by Django 4.1.7 on 2023-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Method',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Airtel', 'Airtel'), ('Master Card', 'Master Card')], max_length=100, null=True),
        ),
    ]
