# Generated by Django 4.1.7 on 2023-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_subscription_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Method',
            field=models.CharField(choices=[('MTN MOMO', 'MTN MOMO'), ('Airtel Money', 'Airtel Money'), ('Master Card', 'Master Card')], max_length=100, null=True),
        ),
    ]
