# Generated by Django 3.2 on 2023-06-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
        ('Subscriptions', '0005_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Method',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Mobile_Number',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Status',
        ),
        migrations.AddField(
            model_name='subscription',
            name='Payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.payment'),
        ),
    ]
