# Generated by Django 4.1.7 on 2023-02-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_student_school'),
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(related_name='school_children', to='Students.student'),
        ),
    ]
