# Generated by Django 4.1.7 on 2023-02-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
        ('Schools', '0002_school_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(to='Classes.class'),
        ),
    ]
