# Generated by Django 4.1.7 on 2023-03-08 16:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_school_events_school_examinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='badge',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='Schools/Badges'),
        ),
    ]
