# Generated by Django 4.1.7 on 2023-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0005_school_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='airtel_account',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='mtn_account',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
