# Generated by Django 4.1.7 on 2023-03-17 06:32

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0005_class_from_class_to'),
        ('Students', '0009_alter_student_photo'),
        ('Schools', '0006_school_airtel_account_school_mtn_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='airtel_account',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='badge',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Schools/Badges'),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(blank=True, to='Classes.class'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mtn_account',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='school_children', to='Students.student'),
        ),
    ]
