# Generated by Django 4.1.7 on 2023-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0001_initial'),
        ('Schools', '0007_alter_school_airtel_account_alter_school_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Divisions',
            field=models.ManyToManyField(blank=True, to='Grading.division'),
        ),
        migrations.AddField(
            model_name='school',
            name='Grades',
            field=models.ManyToManyField(blank=True, to='Grading.grade'),
        ),
    ]
