# Generated by Django 4.1.7 on 2023-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_alter_subject_name'),
        ('Schools', '0008_school_divisions_school_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Subjects',
            field=models.ManyToManyField(blank=True, to='Subjects.subject'),
        ),
    ]
