# Generated by Django 4.1.7 on 2023-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0002_alter_lesson_unique_together'),
        ('Schools', '0010_school_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Lessons',
            field=models.ManyToManyField(blank=True, to='Lessons.lesson'),
        ),
    ]
