# Generated by Django 4.1.7 on 2023-03-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circulars', '0001_initial'),
        ('Schools', '0011_school_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Circulars',
            field=models.ManyToManyField(blank=True, to='Circulars.circular'),
        ),
    ]
