# Generated by Django 4.1.7 on 2023-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0012_workprofile_lessons'),
        ('Schools', '0012_school_circulars'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Teachers',
            field=models.ManyToManyField(blank=True, to='Teachers.teacher'),
        ),
    ]
