# Generated by Django 4.1.7 on 2023-03-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0014_school_dues'),
        ('Terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Terms.term'),
        ),
    ]
