# Generated by Django 4.1.7 on 2023-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollments', '0002_enrollment_programme_alter_enrollment_date'),
        ('Schools', '0016_school_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Enrollments',
            field=models.ManyToManyField(blank=True, to='Enrollments.enrollment'),
        ),
    ]
