# Generated by Django 4.1.7 on 2023-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0004_schooladministrator_role'),
        ('Schools', '0018_school_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Administrators',
            field=models.ManyToManyField(to='SchoolAdministrators.schooladministrator'),
        ),
    ]
