# Generated by Django 4.1.7 on 2023-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0003_remove_parent_children_relationship_and_more'),
        ('SchoolAdministrators', '0004_schooladministrator_role'),
        ('Schools', '0019_school_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Parents',
            field=models.ManyToManyField(blank=True, to='Parents.parent'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Administrators',
            field=models.ManyToManyField(blank=True, to='SchoolAdministrators.schooladministrator'),
        ),
    ]
