# Generated by Django 4.1.7 on 2023-04-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0020_school_parents_alter_school_administrators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='Administrators',
        ),
    ]
