# Generated by Django 4.1.7 on 2023-04-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdministrators', '0015_adminship_last_login'),
        ('Schools', '0021_remove_school_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Administrators',
            field=models.ManyToManyField(through='SchoolAdministrators.Adminship', to='SchoolAdministrators.schooladministrator'),
        ),
    ]
