# Generated by Django 4.1.7 on 2023-04-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Terms', '0001_initial'),
        ('Schools', '0022_school_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='current_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Terms.term'),
        ),
    ]
