# Generated by Django 4.1.7 on 2023-04-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0001_initial'),
        ('Schools', '0023_alter_school_current_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Books',
            field=models.ManyToManyField(blank=True, to='LibraryManagement.book'),
        ),
    ]
