# Generated by Django 4.1.7 on 2023-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0003_remove_parent_children_relationship_and_more'),
        ('Schools', '0025_remove_school_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Parents',
            field=models.ManyToManyField(blank=True, to='Parents.parent'),
        ),
    ]
