# Generated by Django 4.1.7 on 2023-04-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0001_initial'),
        ('Schools', '0026_school_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Programmes',
            field=models.ManyToManyField(blank=True, to='Programmes.programme'),
        ),
    ]
