# Generated by Django 4.1.7 on 2023-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SickBay', '0001_initial'),
        ('Schools', '0027_school_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='patient_admissions',
            field=models.ManyToManyField(blank=True, to='SickBay.admission'),
        ),
    ]
