# Generated by Django 4.1.7 on 2023-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkSheets', '0001_initial'),
        ('Schools', '0028_school_patient_admissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mark_sheets',
            field=models.ManyToManyField(blank=True, to='MarkSheets.marksheet'),
        ),
    ]
