# Generated by Django 4.1.7 on 2023-04-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
        ('Schools', '0029_school_mark_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Applications',
            field=models.ManyToManyField(related_name='parent_applications', to='Applications.application'),
        ),
    ]
