# Generated by Django 4.1.7 on 2023-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationHistory', '0001_initial'),
        ('Students', '0016_student_education_history'),
        ('Schools', '0031_school_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='old_students',
            field=models.ManyToManyField(related_name='school_old_students', through='EducationHistory.EducationHistory', to='Students.student'),
        ),
    ]
