# Generated by Django 4.1.7 on 2023-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0033_alter_school_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
