# Generated by Django 4.1.7 on 2023-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0034_school_motto_alter_school_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(choices=[('Uganda', 'Uganda')], max_length=100),
        ),
    ]
