# Generated by Django 3.2 on 2023-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0035_alter_school_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='setup_step',
            field=models.CharField(choices=[('levels', 'levels')], max_length=20, null=True),
        ),
    ]
