# Generated by Django 3.2 on 2023-05-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0036_school_setup_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='Teachers',
        ),
    ]
