# Generated by Django 3.2 on 2023-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0008_auto_20230517_0725'),
        ('Schools', '0038_school_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Combinations',
            field=models.ManyToManyField(blank=True, to='Subjects.Combination'),
        ),
    ]
