# Generated by Django 4.1.7 on 2023-03-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer Studies', 'Computer Studies'), ('Social Studies', 'Social Studies'), ('Geograpghy', 'Geography'), ('Christian Religious Education', 'Christian Religious Education'), ('Islamic Religious Education', 'Islamic Religious Education')], max_length=100),
        ),
    ]
