# Generated by Django 4.1.7 on 2023-03-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_alter_student_photo'),
        ('Teachers', '0008_remove_teacher_email'),
        ('Subjects', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Head_Of_Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HOD', to='Teachers.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Students',
            field=models.ManyToManyField(to='Students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Teachers',
            field=models.ManyToManyField(to='Teachers.teacher'),
        ),
    ]
