# Generated by Django 4.1.7 on 2023-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0004_alter_subject_head_of_department_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Drawing', 'Drawing'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer Studies', 'Computer Studies'), ('Social Studies', 'Social Studies'), ('Geography', 'Geography'), ('Christian Religious Education', 'Christian Religious Education'), ('Islamic Religious Education', 'Islamic Religious Education')], max_length=100),
        ),
    ]
