# Generated by Django 4.1.7 on 2023-04-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0005_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Drawing', 'Drawing'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer Studies', 'Computer Studies'), ('Social Studies', 'Social Studies'), ('Geography', 'Geography'), ('Christian Religious Education', 'Christian Religious Education'), ('Islamic Religious Education', 'Islamic Religious Education'), ('History', 'History'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Turkish', 'Turkish')], max_length=100),
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Principals', models.ManyToManyField(blank=True, to='Subjects.subject')),
                ('Subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary', to='Subjects.subject')),
            ],
        ),
    ]
