# Generated by Django 4.1.7 on 2023-05-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levels', '0004_level_students'),
        ('Subjects', '0006_alter_subject_name_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Levels',
            field=models.ManyToManyField(blank=True, to='Levels.level'),
        ),
    ]
