# Generated by Django 3.2 on 2023-05-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0038_school_teachers'),
        ('Students', '0019_student_qr_code'),
        ('Subjects', '0007_subject_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
        migrations.AddField(
            model_name='combination',
            name='Students',
            field=models.ManyToManyField(blank=True, to='Students.Student'),
        ),
    ]
