# Generated by Django 3.2 on 2023-05-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0039_school_combinations'),
        ('Subjects', '0008_auto_20230517_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional')], max_length=100, null=True),
        ),
    ]
