# Generated by Django 3.2 on 2023-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0009_auto_20230518_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
