# Generated by Django 3.2 on 2023-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parents', '0005_parent_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(max_length=1000)),
                ('Parents', models.ManyToManyField(to='Parents.Parent')),
            ],
        ),
    ]
