# Generated by Django 3.2 on 2023-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BroadCasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
