# Generated by Django 4.1.7 on 2023-04-30 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0008_class_index'),
        ('Teachers', '0014_teacher_teachinghistory'),
        ('Streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.class'),
        ),
        migrations.AddField(
            model_name='stream',
            name='Class_Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher'),
        ),
    ]
