# Generated by Django 4.1.7 on 2023-04-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary Ordinary Level', 'Secondary Ordinary'), ('Secondary Advanced Level', 'Secondary Advanced'), ('Tertiary', 'Tertiary')], max_length=100)),
            ],
        ),
    ]
