# Generated by Django 4.1.7 on 2023-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0006_alter_subject_name_combination'),
        ('Classes', '0007_class_lessons_alter_class_class_teacher_and_more'),
        ('Levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='Classes',
            field=models.ManyToManyField(to='Classes.class'),
        ),
        migrations.AddField(
            model_name='level',
            name='Subjects',
            field=models.ManyToManyField(to='Subjects.subject'),
        ),
    ]
