# Generated by Django 4.1.7 on 2023-04-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0031_school_levels'),
        ('Levels', '0002_level_classes_level_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
    ]
