# Generated by Django 4.1.7 on 2023-03-10 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0002_alter_subject_name'),
        ('Schools', '0005_school_badge'),
        ('Teachers', '0007_remove_teacher_work_prifile_teacher_work_profile'),
        ('Classes', '0005_class_from_class_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('From', models.TimeField(default=django.utils.timezone.now)),
                ('To', models.TimeField(default=django.utils.timezone.now)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.class')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher')),
            ],
        ),
    ]
