# Generated by Django 4.1.7 on 2023-03-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_alter_subject_name'),
        ('Classes', '0005_class_from_class_to'),
        ('Teachers', '0007_remove_teacher_work_prifile_teacher_work_profile'),
        ('Schools', '0005_school_badge'),
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('School', 'Class', 'Teacher', 'Subject', 'Day')},
        ),
    ]
