# Generated by Django 3.2 on 2023-05-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0008_rollcall'),
        ('Lessons', '0004_lesson_roll_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Roll_Call',
        ),
        migrations.AddField(
            model_name='lesson',
            name='Roll_Calls',
            field=models.ManyToManyField(to='Attendance.RollCall'),
        ),
    ]
