# Generated by Django 4.1.7 on 2023-03-08 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Students', models.PositiveIntegerField(default=0)),
                ('Teacher', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
