# Generated by Django 4.1.7 on 2023-03-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_school_events_school_examinations'),
        ('Attendance', '0002_attendance_remove_teacherattendance_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school'),
        ),
    ]
