# Generated by Django 4.1.7 on 2023-03-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_class_class_teacher'),
        ('Attendance', '0003_attendance_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.class'),
        ),
    ]
