# Generated by Django 4.1.7 on 2023-03-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_class_class_teacher'),
        ('Schools', '0009_school_subjects'),
        ('Attendance', '0004_attendance_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('Date', 'School', 'Class')},
        ),
    ]
