# Generated by Django 4.1.7 on 2023-03-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Teacher',
        ),
    ]
