# Generated by Django 4.1.7 on 2023-03-25 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_alter_student_photo'),
        ('Lessons', '0002_alter_lesson_unique_together'),
        ('Attendance', '0007_alter_attendance_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Attendees', models.ManyToManyField(blank=True, to='Students.student')),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.lesson')),
            ],
        ),
    ]
