# Generated by Django 4.1.7 on 2023-03-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0003_school_classes'),
        ('Reports', '0001_initial'),
        ('Examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='Reports',
            field=models.ManyToManyField(to='Reports.report'),
        ),
        migrations.AddField(
            model_name='examination',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school'),
        ),
    ]
