# Generated by Django 4.1.7 on 2023-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
        ('Examinations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='Reports',
            field=models.ManyToManyField(blank=True, to='Reports.report'),
        ),
    ]
