# Generated by Django 4.1.7 on 2023-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
        ('Examinations', '0003_examination_date_alter_examination_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='Classes',
            field=models.ManyToManyField(blank=True, to='Classes.class'),
        ),
    ]
