# Generated by Django 3.2 on 2023-05-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0007_subject_levels'),
        ('Examinations', '0005_examination_open_to_tallying_examination_mark_sheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(null=True)),
                ('Duration', models.CharField(max_length=10)),
                ('Examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examinations.examination')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject')),
            ],
        ),
    ]
