# Generated by Django 3.2 on 2023-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examinations', '0006_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='Papers',
            field=models.ManyToManyField(to='Examinations.Paper'),
        ),
    ]
