# Generated by Django 3.2 on 2023-05-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0014_teacher_teachinghistory'),
        ('Examinations', '0007_examination_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Examiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher'),
        ),
    ]
