# Generated by Django 3.2 on 2023-05-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0010_class_candidate_class'),
        ('Examinations', '0008_paper_examiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.class'),
        ),
    ]
