# Generated by Django 3.2 on 2023-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examinations', '0009_paper_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Denominator',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
