# Generated by Django 3.2 on 2023-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examinations', '0010_paper_denominator'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
