# Generated by Django 3.2 on 2023-05-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examinations', '0011_paper_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
