# Generated by Django 3.2 on 2023-05-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PastPapers', '0011_remove_pastpaper_description'),
        ('Examinations', '0014_paper_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PastPapers.pastpaper'),
        ),
    ]
